import themeConfig from '@/theme/themeConfig'
import { ConfigProvider } from 'antd'
import { Inter } from 'next/font/google'
import React from 'react'

import StyledComponentsRegistry from '@/lib/AntdRegistry'
import LayoutWrapper from '@/components/LayoutWrapper'

import '@/styles/globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={inter.className}>
      <StyledComponentsRegistry>
        <ConfigProvider theme={themeConfig}>
          <LayoutWrapper>{children}</LayoutWrapper>
        </ConfigProvider>
      </StyledComponentsRegistry>
    </body>
  </html>
)

export default RootLayout
